### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Shubh-k04** [0glabs/0g-doc#1]
I think there is an error in `docs\0G Storage\incentive-mechanism\mining-reward.md` in the line "0G Storage creates pricing segments every 8 GB of data chunks over the **data ow**".
The term "data ow" appears as incorrect and might not convey the intended meaning. It's possible that the intended term was "data flow." This typo could lead to confusion or misinterpretation of the sentence. I suggest replacing "data ow" with "data flow" for clarity and accuracy.
![Screenshot 2024-03-22 012654](https://github.com/0glabs/0g-doc/assets/81859951/c9bc3fb0-e394-49a8-95e8-07db8ba352c3)

**Comment by 0g-peterzhb** [comment]
Thanks! It's fixed now.
