### ISSUE TITLE
How can I run validator node

### ISSUE THREAD

**Issue by fewensa** [0glabs/0g-doc#2]
I'm try to run a validator node follow your document https://github.com/0glabs/0g-doc/blob/main/run-a-node/validator-node.md

It's look like you removed repository https://github.com/0glabs/0g-evmos.git so now how to run this?

**Comment by manan-m-shah** [comment]
Any update on this one? Also, do you have pre-compiled binaries available for download until this issue is resolved?

**Comment by mhlxs** [comment]
pre-compiled binaries is available by getting from : 
`wget https://rpc-zero-gravity-testnet.trusted-point.com/evmosd`

**Comment by manan-m-shah** [comment]
I believe the repo link has been updated to https://github.com/0glabs/0g-chain.git.
@fewensa can close this issue.
